# useful to profile with zprof
# zmodload zsh/zprof
#
#
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
 source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

alias note="cd /Users/lmolteni/Library/Mobile\ Documents/9CR7T2DMDG\~com\~ngocluu\~onewriter/Documents/note"

#
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
 [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

[ -s "/Users/lmolteni/.jabba/jabba.sh" ] && source "/Users/lmolteni/.jabba/jabba.sh"
export PATH="/Users/lmolteni/maven/apache-maven-3.8.3/bin:/usr/local/opt/ant@1.9/bin:$PATH"

